AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for GitHub Actions to deploy SAM applications

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsDeployRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:SatoshiMoriyama/iam-policy-autopilot-test:*
      Policies:
        - PolicyName: SAMDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplateSummary
                  - cloudformation:DescribeChangeSet
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                Resource: arn:aws:cloudformation:ap-northeast-1:853835738220:stack/*/*
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - arn:aws:s3:::aws-sam-cli-managed-default-*
                  - arn:aws:s3:::aws-sam-cli-managed-default-*/*
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:ListTags
                  - lambda:TagResource
                  - lambda:UntagResource
                Resource: arn:aws:lambda:ap-northeast-1:853835738220:function:*
              - Effect: Allow
                Action:
                  - apigateway:POST
                  - apigateway:PATCH
                  - apigateway:DELETE
                  - apigateway:GET
                  - apigateway:PUT
                Resource: arn:aws:apigateway:ap-northeast-1::/*
              - Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:UpdateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - dynamodb:TagResource
                  - dynamodb:UntagResource
                Resource: arn:aws:dynamodb:ap-northeast-1:853835738220:table/*
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PassRole
                  - iam:GetRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                Resource: arn:aws:iam::853835738220:role/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:PutRetentionPolicy
                  - logs:TagResource
                  - logs:UntagResource
                Resource: arn:aws:logs:ap-northeast-1:853835738220:log-group:*

Outputs:
  RoleArn:
    Description: ARN of the GitHub Actions IAM Role
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: GitHubActionsDeployRoleArn
